#pragma once

// Protocol-only MCP server core.  This header deliberately has no dependency
// on er2, VMMDLL, or the DMA adapter.  A backend can register typed handlers
// and keep all target-process state behind its own executor.

#include "mcp/json.hpp"

#include <functional>
#include <map>
#include <set>
#include <string>
#include <vector>

namespace unityexplorer::mcp {

using Json = nlohmann::json;

struct ServerInfo {
  std::string name = "UnityExplorerMcpServer";
  std::string version = "0.1.0";
  std::string protocolVersion = "2026-07-28";
};

// The transport/authentication layer owns the identity and scopes.  Metadata
// is retained for tracing, but client-supplied metadata is never promoted to
// authorization scopes by McpServer itself.
struct RequestContext {
  std::string clientId;
  std::set<std::string> scopes;
  Json metadata = Json::object();
};

struct ToolResult {
  bool isError = false;
  std::string text;
  Json structuredContent = Json::object();
  Json content = Json::array();

  static ToolResult Success(Json data = Json::object(),
                            std::string text = {});
  static ToolResult Failure(std::string code, std::string message,
                            Json data = Json::object());

  // Encodes the result required by tools/call.  Business failures remain a
  // normal JSON-RPC result with isError=true; protocol failures use a JSON-RPC
  // error object generated by McpServer.
  Json ToMcpResult() const;
};

using ToolHandler =
    std::function<ToolResult(const Json &arguments, const RequestContext &)>;

struct ToolDefinition {
  std::string name;
  std::string description;
  Json inputSchema = Json{{"type", "object"},
                          {"properties", Json::object()},
                          {"additionalProperties", false}};
  Json outputSchema = Json{{"type", "object"}};
  std::vector<std::string> requiredScopes;
  ToolHandler handler;
};

struct McpServerOptions {
  ServerInfo serverInfo;
  bool exposeResourcesCapability = false;
  bool exposePromptsCapability = false;
  bool allowLegacyInitialize = true;
  std::size_t maxLineBytes = 4u * 1024u * 1024u;
};

class McpServer final {
public:
  explicit McpServer(McpServerOptions options = {});

  const ServerInfo &GetServerInfo() const noexcept {
    return options_.serverInfo;
  }

  const McpServerOptions &GetOptions() const noexcept { return options_; }

  // Registration is expected during startup.  Re-registering a name replaces
  // the old definition, which makes backend wiring deterministic in tests and
  // in a future plugin/module configuration.
  bool RegisterTool(ToolDefinition definition);
  bool RemoveTool(const std::string &name);
  void ClearTools();

  std::vector<ToolDefinition> ListToolDefinitions() const;

  // Returns a JSON-RPC response.  A null JSON value means the request was a
  // notification and must not be written to the transport.
  Json HandleRequest(const Json &request,
                     const RequestContext &context = {}) const;

  // Parses one newline-delimited JSON-RPC frame.  Parse errors are converted
  // to a JSON-RPC error response.  Empty lines and notifications return an
  // empty string, so callers can simply skip writing them.
  std::string HandleLine(const std::string &line,
                         const RequestContext &context = {}) const;

private:
  McpServerOptions options_;
  std::map<std::string, ToolDefinition> tools_;

  Json MakeErrorResponse(const Json &id, int code, const std::string &message,
                         Json data = Json::object()) const;
  Json MakeResultResponse(const Json &id, Json result) const;
  Json BuildCapabilities() const;
  Json BuildDiscoverResult() const;
  Json BuildInitializeResult(const Json &params) const;
  Json BuildToolsListResult() const;

  static bool IsValidRequestId(const Json &id);
  static bool ValidateSchema(const Json &value, const Json &schema,
                             std::string &error, const std::string &path);
  static bool HasRequiredScopes(const RequestContext &context,
                                const ToolDefinition &tool,
                                std::string &missingScope);
  static RequestContext ContextFromRequest(const Json &request,
                                           const RequestContext &base);
};

} // namespace unityexplorer::mcp
